// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_4Su6qvbu5RPjE59QPYyFOK5I-XkVIc',
    appId: '1:1081400267918:web:08858e24f414de9c81a5df',
    messagingSenderId: '1081400267918',
    projectId: 'untitled-981ae',
    authDomain: 'untitled-981ae.firebaseapp.com',
    storageBucket: 'untitled-981ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUhK--ueIbbdInXEmw1R2yhy1wWxLteno',
    appId: '1:1081400267918:android:4204bd4085ffda7c81a5df',
    messagingSenderId: '1081400267918',
    projectId: 'untitled-981ae',
    storageBucket: 'untitled-981ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEMDsUF1AqAst-LeD2cFNrRpmq2Ni3_Yw',
    appId: '1:1081400267918:ios:e8a4e5b315c378e281a5df',
    messagingSenderId: '1081400267918',
    projectId: 'untitled-981ae',
    storageBucket: 'untitled-981ae.appspot.com',
    iosClientId: '1081400267918-29cgnp2md15fo12i0j9o8jd3sa9dmahn.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEMDsUF1AqAst-LeD2cFNrRpmq2Ni3_Yw',
    appId: '1:1081400267918:ios:e8a4e5b315c378e281a5df',
    messagingSenderId: '1081400267918',
    projectId: 'untitled-981ae',
    storageBucket: 'untitled-981ae.appspot.com',
    iosClientId: '1081400267918-29cgnp2md15fo12i0j9o8jd3sa9dmahn.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
